# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nAIWdzMBQ7FF6KJ448otLR5UZpScBGjc
"""

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

data = pd.read_csv("https://raw.githubusercontent.com/amankharwal/Website-data/master/dataset.csv")
data.head(5)

cv = CountVectorizer()
x = np.array(data['Text'])
y = np.array(data['language'])
x_new = cv.fit_transform(x)

x_train,x_test,y_train,y_test = train_test_split(x_new,y,random_state=42,test_size=0.33)

model = MultinomialNB()
model.fit(x_train,y_train)
model.score(x_test,y_test)

while True:
  user = input("Enter a Text or type (q or exit) to leave: ")
  if user.lower() == 'q' or user.lower() == "exit":
    break
  data = cv.transform([user]).toarray()
  output = model.predict(data)
  print(output)